# ── Build stage ──────────────────────────────────────────────
FROM golang:1.22-alpine AS builder

WORKDIR /src

# Copy only go.mod first so dependency layer is cached independently
# of source changes. go.sum will be generated by go mod tidy.
COPY go.mod ./
RUN go mod download || true

COPY . .
# go mod tidy regenerates go.sum and fetches any missing modules.
RUN go mod tidy && \
    CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /telemod ./cmd/bot

# ── Runtime stage ─────────────────────────────────────────────
FROM alpine:3.20

RUN apk add --no-cache ca-certificates tzdata
WORKDIR /app

COPY --from=builder /telemod /app/telemod

ENTRYPOINT ["/app/telemod"]
